# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Install a corrected CTestTestfile.cmake that supersedes the one generated by
# rocm-libraries. The rocm-libraries version uses bare `python` (which may not
# exist in the test environment) and relative test paths. This version uses
# `python3` and CMAKE_CURRENT_LIST_DIR-relative paths that resolve correctly
# wherever the artifact is unpacked.
#
# LD_LIBRARY_PATH and PYTHONPATH are set by test_origami.py before invoking
# ctest, so no ENVIRONMENT property is needed here.

if(NOT THEROCK_BUILD_TESTING)
  return()
endif()

# Bracket string prevents cmake from expanding ${CMAKE_CURRENT_LIST_DIR} here;
# it is written literally so ctest expands it when reading the installed file.
set(_ctest_content [=[
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

# C++ tests
add_test(origami-tests "${CMAKE_CURRENT_LIST_DIR}/../origami-tests")
set_tests_properties(origami-tests PROPERTIES
    LABELS "cpp"
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
)

# Python tests (using pytest)
# LD_LIBRARY_PATH and PYTHONPATH are set by the test runner (test_origami.py).
add_test(origami_python_tests python3 -m pytest "${CMAKE_CURRENT_LIST_DIR}/tests" -v)
set_tests_properties(origami_python_tests PROPERTIES
    LABELS "python"
    SKIP_RETURN_CODE 5
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
)
]=])

file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/CTestTestfile.cmake.therock" "${_ctest_content}")

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/CTestTestfile.cmake.therock"
    DESTINATION "${CMAKE_INSTALL_BINDIR}/origami"
    COMPONENT tests
    RENAME CTestTestfile.cmake
)
